// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class CategoryPriceList
{
    public int Id { get; set; }

    public int? Sno { get; set; }

    public DateTime? Adate { get; set; }

    public string Tcode { get; set; }

    public decimal? Rate { get; set; }

    public string Pcode { get; set; }

    public short? Code { get; set; }

    public string Typ { get; set; }

    public string CatCode { get; set; }

    public decimal? Ipdrate { get; set; }

    public string Editable { get; set; }

    public decimal? MinCharges { get; set; }

    public decimal? MaxCharges { get; set; }

    public string DiscountApp { get; set; }

    public string TimeBound { get; set; }

    public string OutSource { get; set; }

    public string Descript { get; set; }

    public string CpcName { get; set; }

    public DateTime? EntryTime { get; set; }

    public string User { get; set; }

    public string IsActive { get; set; }
}