// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class DoctorWeeklySchedule
{
    public int ScheduleId { get; set; }

    public int UserDoctorId { get; set; }

    public int UnitId { get; set; }

    public byte DayOfWeek { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public int? ShiftId { get; set; }

    public int? MaxPatients { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ShiftMaster Shift { get; set; }
}