// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DWB.Models;

public partial class DWBEntity : DbContext
{
    public DWBEntity(DbContextOptions<DWBEntity> options)
        : base(options)
    {
    }

    public virtual DbSet<TblDietMaster> TblDietMaster { get; set; }

    public virtual DbSet<TblFloorMaster> TblFloorMaster { get; set; }

    public virtual DbSet<TblRoleMas> TblRoleMas { get; set; }

    public virtual DbSet<TblRoomMaster> TblRoomMaster { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblDietMaster>(entity =>
        {
            entity.HasKey(e => new { e.IntId, e.IntUnitCode });

            entity.ToTable("tblDietMaster");

            entity.Property(e => e.IntId)
                .ValueGeneratedOnAdd()
                .HasColumnName("intID");
            entity.Property(e => e.IntUnitCode).HasColumnName("intUnitCode");
            entity.Property(e => e.BitIsDeactivated).HasColumnName("bitIsDeactivated");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.DtUpdated)
                .HasColumnType("datetime")
                .HasColumnName("dtUpdated");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .HasColumnName("vchCreatedBy");
            entity.Property(e => e.VchDescript)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("vchDescript");
            entity.Property(e => e.VchDietCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("vchDietCode");
            entity.Property(e => e.VchDietName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("vchDietName");
            entity.Property(e => e.VchIpUpdated)
                .HasMaxLength(20)
                .HasColumnName("vchIpUpdated");
            entity.Property(e => e.VchIpUsed)
                .HasMaxLength(20)
                .HasColumnName("vchIpUsed");
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("vchUpdatedBy");
        });

        modelBuilder.Entity<TblFloorMaster>(entity =>
        {
            entity.HasKey(e => new { e.IntId, e.IntUnitCode });

            entity.ToTable("tblFloorMaster");

            entity.Property(e => e.IntId)
                .ValueGeneratedOnAdd()
                .HasColumnName("intID");
            entity.Property(e => e.IntUnitCode).HasColumnName("intUnitCode");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.DtUpdated)
                .HasColumnType("datetime")
                .HasColumnName("dtUpdated");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchCreatedBy");
            entity.Property(e => e.VchFloor)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchFloor");
            entity.Property(e => e.VchIpUpdated)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("vchIpUpdated");
            entity.Property(e => e.VchIpUsed)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("vchIpUsed");
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("vchUpdatedBy");
        });

        modelBuilder.Entity<TblRoleMas>(entity =>
        {
            entity.HasKey(e => e.IntId);

            entity.ToTable("tblRoleMas");

            entity.Property(e => e.IntId).HasColumnName("intID");
            entity.Property(e => e.BitIsActive).HasDefaultValue(true);
            entity.Property(e => e.DtCreated)
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.DtUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtUpdated");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .HasColumnName("vchCreatedBy");
            entity.Property(e => e.VchIpUpdated)
                .HasMaxLength(50)
                .HasColumnName("vchIpUpdated");
            entity.Property(e => e.VchIpUsed)
                .HasMaxLength(30)
                .HasColumnName("vchIpUsed");
            entity.Property(e => e.VchRole)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("vchRole");
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("vchUpdatedBy");
        });

        modelBuilder.Entity<TblRoomMaster>(entity =>
        {
            entity.HasKey(e => new { e.IntId, e.IntUnitCode });

            entity.ToTable("tblRoomMaster");

            entity.Property(e => e.IntId)
                .ValueGeneratedOnAdd()
                .HasColumnName("intID");
            entity.Property(e => e.IntUnitCode).HasColumnName("intUnitCode");
            entity.Property(e => e.BitIsDeactivated).HasColumnName("bitIsDeactivated");
            entity.Property(e => e.DtCreated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("dtCreated");
            entity.Property(e => e.DtUpdated)
                .HasColumnType("datetime")
                .HasColumnName("dtUpdated");
            entity.Property(e => e.FkIntFloorId).HasColumnName("fk_intFloorId");
            entity.Property(e => e.IntRoomNo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("intRoomNo");
            entity.Property(e => e.VchCreatedBy)
                .HasMaxLength(50)
                .HasColumnName("vchCreatedBy");
            entity.Property(e => e.VchIpUpdated)
                .HasMaxLength(20)
                .HasColumnName("vchIpUpdated");
            entity.Property(e => e.VchIpUsed)
                .HasMaxLength(20)
                .HasColumnName("vchIpUsed");
            entity.Property(e => e.VchUpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("vchUpdatedBy");

            entity.HasOne(d => d.TblFloorMaster).WithMany(p => p.TblRoomMaster)
                .HasForeignKey(d => new { d.FkIntFloorId, d.IntUnitCode })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tblRoomMaster_tblFloorMaster");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}