// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DWB.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DWB.Models
{
    public partial class DWBEntity
    {
        private IDWBEntityProcedures _procedures;

        public virtual IDWBEntityProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DWBEntityProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDWBEntityProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class DWBEntityProcedures : IDWBEntityProcedures
    {
        private readonly DWBEntity _context;

        public DWBEntityProcedures(DWBEntity context)
        {
            _context = context;
        }

        public virtual async Task<List<spGetLabTestResult>> spGetLabTestAsync(string term, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "term",
                    Size = 200,
                    Value = term ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetLabTestResult>("EXEC @returnValue = [dbo].[spGetLabTest] @term = @term", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spGetRadioProcedureResult>> spGetRadioProcedureAsync(string type, string search, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Type",
                    Size = 100,
                    Value = type ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Search",
                    Size = 200,
                    Value = search ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetRadioProcedureResult>("EXEC @returnValue = [dbo].[spGetRadioProcedure] @Type = @Type, @Search = @Search", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spSearchMedicinesResult>> spSearchMedicinesAsync(string searchTerm, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "SearchTerm",
                    Size = 200,
                    Value = searchTerm ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spSearchMedicinesResult>("EXEC @returnValue = [dbo].[spSearchMedicines] @SearchTerm = @SearchTerm", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
