// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class EmergencyTriageAssessment
{
    public long BigintAssessmentId { get; set; }

    public long BigintVisitId { get; set; }

    public string VchPatientId { get; set; }

    public DateTime DtCreatedDate { get; set; }

    public long BigintCreatedByDoctorId { get; set; }

    public string VchCreatedByDoctorName { get; set; }

    public string VchDoctorCode { get; set; }

    public string VchPatientName { get; set; }

    public string VchUhidNo { get; set; }

    public string VchAge { get; set; }

    public string VchSex { get; set; }

    public string VchPhoneNumber { get; set; }

    public string VchAddress { get; set; }

    public string VchRoomWardNumber { get; set; }

    public string VchBedNumber { get; set; }

    public DateTime DtArrivalDateTime { get; set; }

    public DateTime DtTimeSeenByProvider { get; set; }

    public string VchTransportationMode { get; set; }

    public string VchTransportationOther { get; set; }

    public string VchHistoryObtainedFrom { get; set; }

    public DateTime? DtVitalsTime { get; set; }

    public string VchPulse { get; set; }

    public int? IntBpsystolic { get; set; }

    public int? IntBpdiastolic { get; set; }

    public int? IntRespRate { get; set; }

    public decimal? DecTemperature { get; set; }

    public decimal? DecWeight { get; set; }

    public string VchChiefComplaint { get; set; }

    public string VchCurrentMedication { get; set; }

    public string VchAllergies { get; set; }

    public string VchSubjectiveNotes { get; set; }

    public string VchObjectiveNotes { get; set; }

    public string VchInvestigationsOrdered { get; set; }

    public string VchProvisionalDiagnosis { get; set; }

    public string VchTreatmentPlan { get; set; }

    public string VchTriageCategory { get; set; }

    public string VchConditionUponRelease { get; set; }

    public DateTime? DtDischargeDateTime { get; set; }

    public bool? BitIsAdmissionAdvised { get; set; }

    public string VchAdmissionRefusalReason { get; set; }

    public bool? BitIsCrossConsultRequired { get; set; }

    public string VchSpecialistName { get; set; }

    public string VchReferredTo { get; set; }

    public DateTime? DtFollowUpDate { get; set; }

    public DateTime? DtFollowUpTime { get; set; }

    public string VchPatientInstructions { get; set; }

    public string VchRemarks { get; set; }

    public bool BitIsCompleted { get; set; }

    public int IntCode { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public int IntIhmscode { get; set; }

    public string Vchdocname { get; set; }

    public string VchCatCode { get; set; }

    public string VchCategory { get; set; }

    public int? ConsultantDoctorId { get; set; }

    public string OtherDoctorName { get; set; }
}