// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class EmergencyTriageAssessment
{
    public long AssessmentId { get; set; }

    public long VisitId { get; set; }

    public string? PatientId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public long CreatedByDoctorId { get; set; }

    public string CreatedByDoctorName { get; set; }

    public string PatientName { get; set; }

    public string MrnNumber { get; set; }

    public string Age { get; set; }

    public string Sex { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string RoomWardNumber { get; set; }

    public string BedNumber { get; set; }

    public DateTime ArrivalDateTime { get; set; }

    public DateTime TimeSeenByProvider { get; set; }

    public string TransportationMode { get; set; }

    public string TransportationOther { get; set; }

    public string HistoryObtainedFrom { get; set; }

    public DateTime? VitalsTime { get; set; }

    public string Pulse { get; set; }

    public int? Bpsystolic { get; set; }

    public int? Bpdiastolic { get; set; }

    public int? RespRate { get; set; }

    public decimal? Temperature { get; set; }

    public decimal? Weight { get; set; }

    public string ChiefComplaint { get; set; }

    public string CurrentMedication { get; set; }

    public string Allergies { get; set; }

    public string SubjectiveNotes { get; set; }

    public string ObjectiveNotes { get; set; }

    public string InvestigationsOrdered { get; set; }

    public string ProvisionalDiagnosis { get; set; }

    public string TreatmentPlan { get; set; }

    public string TriageCategory { get; set; }

    public string ConditionUponRelease { get; set; }

    public DateTime? DischargeDateTime { get; set; }

    public bool? IsAdmissionAdvised { get; set; }

    public string AdmissionRefusalReason { get; set; }

    public bool? IsCrossConsultRequired { get; set; }

    public string SpecialistName { get; set; }

    public string ReferredTo { get; set; }

    public DateTime? FollowUpDate { get; set; }

    public DateTime? FollowUpTime { get; set; }

    public string PatientInstructions { get; set; }

    public string Remarks { get; set; }
}