// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class EstimateLineItem
{
    public int LineItemId { get; set; }

    public int EstimateRecordId { get; set; }

    public string ServiceName { get; set; }

    public string UnitType { get; set; }

    public decimal TariffRate { get; set; }

    public decimal EstimatedQuantity { get; set; }

    public decimal CalculatedAmount { get; set; }

    public bool IsPackageItem { get; set; }

    public virtual PatientEstimateRecord EstimateRecord { get; set; }
}