// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DWB.Models
{
    public partial class GetDoctorAssmtReportPrintResult
    {
        public int intAssessmentId { get; set; }
        [StringLength(150)]
        public string vchHMSName { get; set; }
        public int? intAge { get; set; }
        [StringLength(50)]
        public string vchGender { get; set; }
        public DateTime? dtCreated { get; set; }
        public int intIHMSVisit { get; set; }
    }
}
