// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DWB.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DWB.Models
{
    public partial interface IDWBEntityProcedures
    {
        Task<List<spGetRadioProcedureResult>> spGetRadioProcedureAsync(string type, string search, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSearchMedicinesResult>> spSearchMedicinesAsync(string searchTerm, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
