// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class Imaster
{
    public int IntId { get; set; }

    public string Icode { get; set; }

    public double? Code { get; set; }

    public string Descript { get; set; }

    public string ItemType { get; set; }

    public string ItemAccount { get; set; }

    public string AdjustmentAccount { get; set; }

    public string PpvAccount { get; set; }

    public string SaleAccount { get; set; }

    public string CogsAccount { get; set; }

    public string Uom { get; set; }

    public string Costmethod { get; set; }

    public double? Receiptp { get; set; }

    public double? Receiptm { get; set; }

    public double? Shipmentp { get; set; }

    public double? Shipmentm { get; set; }

    public string Sdwh { get; set; }

    public string Sdsales { get; set; }

    public string Planingtype { get; set; }

    public string LotControl { get; set; }

    public string Vdescript { get; set; }

    public double? SerialNo { get; set; }

    public string ItemStatus { get; set; }

    public double? ClQty { get; set; }

    public double? PurRate { get; set; }

    public double? SaleRate { get; set; }

    public double? MinQty { get; set; }

    public double? MaxQty { get; set; }

    public double? ManuFact { get; set; }

    public double? Purchase { get; set; }

    public double? SubCont { get; set; }

    public double? UsagePrd { get; set; }

    public double? UsageSal { get; set; }

    public double? UsageOth { get; set; }

    public double? BatchNo { get; set; }

    public double? MfgDate { get; set; }

    public double? ExpDate { get; set; }

    public double? Tax { get; set; }

    public string TaxId { get; set; }

    public double? Mcost { get; set; }

    public double? Ccost { get; set; }

    public DateTime? EfDate { get; set; }

    public double? BoxQty { get; set; }

    public string PoUom { get; set; }

    public double? UomCon { get; set; }

    public double? Lenth { get; set; }

    public double? Height { get; set; }

    public string Cuom { get; set; }

    public double? Area { get; set; }

    public double? Feet { get; set; }

    public double? Yard { get; set; }

    public double? Rfeet { get; set; }

    public string Shape { get; set; }

    public string Sz { get; set; }

    public string CSize { get; set; }

    public string LatexType { get; set; }

    public string BackingType { get; set; }

    public string QltyType { get; set; }

    public double? GrossQlty { get; set; }

    public double? NetQlty { get; set; }

    public double? Cweight { get; set; }

    public string Itype { get; set; }

    public string Qual { get; set; }

    public string Quality { get; set; }

    public string Des { get; set; }

    public string Design { get; set; }

    public string Shd { get; set; }

    public string Shade { get; set; }

    public string Col { get; set; }

    public string Colour { get; set; }

    public string Itemtype1 { get; set; }

    public string Mtype { get; set; }

    public string MaterialType { get; set; }

    public double? ReOrderLevel { get; set; }

    public double? ReOrderQty { get; set; }

    public string Muom { get; set; }

    public double? MinLen { get; set; }

    public string PcName { get; set; }

    public DateTime? EnDate { get; set; }

    public string OnLine { get; set; }

    public string Manf { get; set; }

    public string Salt { get; set; }

    public string It { get; set; }

    public string Iname { get; set; }

    public string Itemname { get; set; }

    public string Ig { get; set; }

    public string ItemGroup { get; set; }

    public string Cn { get; set; }

    public string CompName { get; set; }

    public string Ihdescript { get; set; }

    public double? UomCon2 { get; set; }

    public double? BarCode { get; set; }

    public string BarcodeOpt { get; set; }

    public double? MrpFac { get; set; }

    public double? SafetyStock { get; set; }

    public string Tax2 { get; set; }

    public string TrimItem { get; set; }

    public double? VatonD { get; set; }

    public string Weight { get; set; }

    public string HighRisk { get; set; }

    public string SaleDiscount { get; set; }

    public string F101 { get; set; }

    public string F102 { get; set; }

    public string F103 { get; set; }

    public string F104 { get; set; }

    public string F105 { get; set; }

    public string F106 { get; set; }

    public string F107 { get; set; }

    public string HsnCode { get; set; }

    public string Ved { get; set; }

    public string Lookalike { get; set; }

    public string Soundalike { get; set; }

    public string OutofFormerly { get; set; }

    public DateOnly? DtOutofFormerly { get; set; }

    public string UserEntry { get; set; }

    public string EntryComputer { get; set; }

    public string UserUpdate { get; set; }

    public string UpdateComputer { get; set; }

    public bool? IsRestricted { get; set; }

    public int? IntQty { get; set; }

    public string VchPack { get; set; }

    public string VchUnit { get; set; }

    public string Dupicode { get; set; }

    public DateTime? DtAdded { get; set; }

    public short? IsIndentApproved { get; set; }

    public decimal? Gstp { get; set; }

    public short? IsChemo { get; set; }

    public string ItemRemarks { get; set; }
}