// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class PatientEstimateRecord
{
    public int EstimateRecordId { get; set; }

    public string Uhid { get; set; }

    public int VisitNumber { get; set; }

    public string PatientName { get; set; }

    public string CounselorName { get; set; }

    public DateTime EstimateDate { get; set; }

    public decimal TotalEstimatedCost { get; set; }

    public decimal TotalAmountReceived { get; set; }

    public string RelativeName { get; set; }

    public string RelativeRelation { get; set; }

    public bool IsAcknowledged { get; set; }

    public string RelativeSignatureData { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool BitIsCompleted { get; set; }

    public bool BitIscancelled { get; set; }

    public string VchCompletedUser { get; set; }

    public string VchHostName { get; set; }

    public int IntCode { get; set; }

    public int IntIhmscode { get; set; }

    public virtual ICollection<EstimateLineItem> EstimateLineItem { get; set; } = new List<EstimateLineItem>();

    public virtual ICollection<PaymentTransaction> PaymentTransaction { get; set; } = new List<PaymentTransaction>();
}