// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class PaymentTransaction
{
    public int TransactionId { get; set; }

    public int EstimateRecordId { get; set; }

    public DateOnly? PaymentDate { get; set; }

    public decimal? AmountPaid { get; set; }

    public string PayerName { get; set; }

    public string PayerRelation { get; set; }

    public virtual PatientEstimateRecord EstimateRecord { get; set; }
}