// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class ServiceMaster
{
    public string Service { get; set; }

    public string Scode { get; set; }

    public short Code { get; set; }

    public string Depart { get; set; }

    public decimal? Charges { get; set; }

    public string Remarks { get; set; }

    public string Cal { get; set; }

    public string AccountNo { get; set; }

    public string Sname { get; set; }

    public short? Pday { get; set; }

    public string Def { get; set; }

    public string IpdAccount { get; set; }

    public string Sno { get; set; }

    public string Pcode { get; set; }

    public string Status { get; set; }

    public string Ot { get; set; }

    public string Acode { get; set; }

    public string MajorMinor { get; set; }

    public int? Dura { get; set; }

    public string TechCode { get; set; }

    public string SpEqp { get; set; }

    public string SpIns { get; set; }

    public string Tremarks { get; set; }

    public short? Ps { get; set; }

    public int? Ssno { get; set; }

    public string ImScode { get; set; }

    public string ImSno { get; set; }

    public string ImPcode { get; set; }

    public string Tax { get; set; }

    public decimal? Icharges { get; set; }

    public int? Cnt { get; set; }

    public string Mgrp { get; set; }

    public string DisExc { get; set; }

    public int? Gsno { get; set; }

    public string AvailFor { get; set; }

    public string Editable { get; set; }

    public decimal? MinCharges { get; set; }

    public decimal? MaxCharges { get; set; }

    public string ServiceOs { get; set; }

    public decimal? RefundPr { get; set; }

    public string ProvidedDoctor { get; set; }

    public string DiscountApp { get; set; }

    public string TimeBound { get; set; }

    public string AvailUnit { get; set; }

    public string Uom { get; set; }

    public string QtyEditable { get; set; }

    public decimal? DefQty { get; set; }

    public string PayMode { get; set; }

    public short? PkgIcuDays { get; set; }

    public string Dscode { get; set; }

    public decimal? Ratio { get; set; }

    public string MulSit { get; set; }

    public string SubService { get; set; }

    public string Restrict1 { get; set; }

    public decimal? PshareAmount { get; set; }

    public string ACard { get; set; }

    public int? MedAmount { get; set; }

    public string RoomNo { get; set; }

    public decimal? Ncharges { get; set; }

    public decimal? Nicharges { get; set; }

    public string Ns { get; set; }

    public string UpcName { get; set; }

    public string ChargeMode { get; set; }

    public DateTime? DtAdded { get; set; }

    public int IntId { get; set; }
}