// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class ShiftMaster
{
    public int ShiftId { get; set; }

    public string ShiftName { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public virtual ICollection<DoctorWeeklySchedule> DoctorWeeklySchedule { get; set; } = new List<DoctorWeeklySchedule>();
}