// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DWB.Models
{
    public partial class spGetLabTestResult
    {
        [StringLength(160)]
        public string descript { get; set; }
        [StringLength(20)]
        public string tcode { get; set; }
    }
}
