// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DWB.Models
{
    public partial class spGetRadioProcedureResult
    {
        [StringLength(300)]
        public string service { get; set; }
        [StringLength(20)]
        public string scode { get; set; }
    }
}
