// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DWB.Models
{
    public partial class spSearchMedicinesResult
    {
        [StringLength(255)]
        public string descript { get; set; }
        [StringLength(255)]
        public string icode { get; set; }
    }
}
