// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TariffMaster
{
    public int TariffMasterId { get; set; }

    public string ServiceName { get; set; }

    public string UnitType { get; set; }

    public decimal CurrentRate { get; set; }

    public string CalculationType { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string IntCode { get; set; }

    public string IntHmscode { get; set; }

    public string ClientIp { get; set; }

    public string ClientHostName { get; set; }

    public bool BitIsDeafult { get; set; }
}