// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDocTemplateAssessment
{
    public int Intid { get; set; }

    public int IntFkuserid { get; set; }

    public string VchTempleteName { get; set; }

    public string VchChiefComplaints { get; set; }

    public string VchMedicalHistory { get; set; }

    public string VchSystemicExam { get; set; }

    public string VchDiagnosis { get; set; }

    public string VchRemarks { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchCreatdeHost { get; set; }

    public string VchUpdatedHost { get; set; }

    public bool? BitDeactivated { get; set; }

    public string DataJson { get; set; }

    public virtual TblUsers IntFkuser { get; set; }

    public virtual ICollection<TblDocTemplateMedicine> TblDocTemplateMedicine { get; set; } = new List<TblDocTemplateMedicine>();
}