// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDocTempleteLab
{
    public int IntId { get; set; }

    public int FkTempId { get; set; }

    public string VchTestCode { get; set; }

    public string VchTestName { get; set; }

    public string VchPriority { get; set; }

    public string VchRemarks { get; set; }

    public bool BitIscompleted { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdted { get; set; }

    public string VchUpdatedBy { get; set; }
}