// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDoctorAssmntMedicine
{
    public int IntId { get; set; }

    public int FkDocAssmntId { get; set; }

    public string VchMedicineCode { get; set; }

    public string VchMedicineName { get; set; }

    public string VchDosage { get; set; }

    public string VchFrequency { get; set; }

    public string VchDuration { get; set; }

    public string VchInstruction { get; set; }

    public bool BitIsPrn { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public virtual TblDoctorAssessment FkDocAssmnt { get; set; }
}