// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDoctorAssmntProcedure
{
    public int IntId { get; set; }

    public int FkDocAsstId { get; set; }

    public string VchProcedureCode { get; set; }

    public string VchProcedureName { get; set; }

    public string VchPriority { get; set; }

    public string VchRemarks { get; set; }

    public bool BitIsCompleted { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public virtual TblDoctorAssessment FkDocAsst { get; set; }
}