// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDocTempleteMedicine
{
    public int IntId { get; set; }

    public int IntFkTempleteId { get; set; }

    public string VchMedicineCode { get; set; }

    public string VchMedicineName { get; set; }

    public int IntQuantity { get; set; }

    public string VchFrequency { get; set; }

    public string VchDuration { get; set; }

    public string VchInstruction { get; set; }

    public bool BitIsPrn { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public bool BitBbf { get; set; }

    public bool BitAbf { get; set; }

    public bool BitBl { get; set; }

    public bool BitAl { get; set; }

    public bool BitBd { get; set; }

    public bool BitAd { get; set; }

    public string BreakFastTiming { get; set; }

    public string LunchTiming { get; set; }

    public string DinnerTiming { get; set; }

    public virtual TblDocAssessmentTemplete IntFkTemplete { get; set; }
}