// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDietMaster
{
    public int IntId { get; set; }

    public string VchDietName { get; set; }

    public string VchDietCode { get; set; }

    public string VchDescript { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public int IntUnitCode { get; set; }

    public bool BitIsDeactivated { get; set; }
}