// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDoctorAssessmentDoc
{
    public int IntId { get; set; }

    public int IntFkDoctorAssId { get; set; }

    public string VchFileName { get; set; }

    public string VchFilePath { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchCreatedIp { get; set; }

    public string VchCreatedHost { get; set; }

    public bool BitIsForDoctorAssessment { get; set; }

    public virtual TblDoctorAssessment IntFkDoctorAss { get; set; }
}