// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblDoctorAssessment
{
    public int IntId { get; set; }

    public string FkUhid { get; set; }

    public int FkAssessmentId { get; set; }

    public string VchDoctorName { get; set; }

    public string VchChiefcomplaints { get; set; }

    public string VchMedicalHistory { get; set; }

    public string VchSystemicexam { get; set; }

    public string VchDiagnosis { get; set; }

    public string VchRemarks { get; set; }

    public bool BitPrescribeMedicine { get; set; }

    public bool BitPrescribeLabTest { get; set; }

    public bool BitRadioInvestigation { get; set; }

    public bool BitAsstAssigned { get; set; }

    public bool BitAsstCompleted { get; set; }

    public DateTime DtStartTime { get; set; }

    public DateTime DtEndTime { get; set; }

    public TimeOnly? VchTat { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public int? IntCode { get; set; }

    public int? FkVisitNo { get; set; }

    public int? FkDepartmentId { get; set; }

    public int? VchDeptCode { get; set; }

    public bool? BitFollowUp { get; set; }

    public DateTime? DtFollowUpDate { get; set; }

    public TimeOnly? FollowUpTime { get; set; }

    public bool? BitNutritionalConsult { get; set; }

    public bool? BitCrossConsult { get; set; }

    public string FkCrossConsultDocCode { get; set; }

    public string VchCrossConsultName { get; set; }

    public bool? BitIpdconversion { get; set; }

    public string VchIpdConsultantCode { get; set; }

    public string VchIpdconsultName { get; set; }

    public string DtHmsentry { get; set; }

    public virtual TblNsassessment FkAssessment { get; set; }
}