// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblModules
{
    public int IntId { get; set; }

    public string VchMasterModule { get; set; }

    public string VchModule { get; set; }

    public string VchSubModule { get; set; }

    public bool BitDeactivated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchUpdatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public virtual ICollection<TblRoleModuleMap> TblRoleModuleMap { get; set; } = new List<TblRoleModuleMap>();
}