// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblNsassessment
{
    public int IntAssessmentId { get; set; }

    public string VchUhidNo { get; set; }

    public string VchBloodPressure { get; set; }

    public string VchPulse { get; set; }

    public string DecTemperature { get; set; }

    public decimal DecSpO2 { get; set; }

    public decimal DecWeight { get; set; }

    public decimal? DecHeight { get; set; }

    public decimal DecRespiratoryRate { get; set; }

    public decimal DecOxygenFlowRate { get; set; }

    public string VchNurseNotes { get; set; }

    public bool BitIsAssigned { get; set; }

    public bool BitIsCompleted { get; set; }

    public DateTime DtStartTime { get; set; }

    public DateTime DtEndTime { get; set; }

    public TimeOnly? VchTat { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }
}