// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblNsassessment
{
    public int IntAssessmentId { get; set; }

    public string VchUhidNo { get; set; }

    public string VchBloodPressure { get; set; }

    public string VchPulse { get; set; }

    public string DecTemperature { get; set; }

    public decimal DecSpO2 { get; set; }

    public decimal DecWeight { get; set; }

    public decimal? DecHeight { get; set; }

    public decimal DecRespiratoryRate { get; set; }

    public decimal DecOxygenFlowRate { get; set; }

    public string VchNurseNotes { get; set; }

    public bool BitIsAssigned { get; set; }

    public bool BitIsCompleted { get; set; }

    public DateTime DtStartTime { get; set; }

    public DateTime DtEndTime { get; set; }

    public TimeOnly? VchTat { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public string VchHmsdtEntry { get; set; }

    public string VchHmsname { get; set; }

    public string VchHmscategory { get; set; }

    public string VchHmsconsultant { get; set; }

    public string VchHmsage { get; set; }

    public string VchIhmintime { get; set; }

    public bool BitIsAllergical { get; set; }

    public string VchAllergicalDrugs { get; set; }

    public bool BitIsAlcoholic { get; set; }

    public bool BitIsSmoking { get; set; }

    public string VchLmpForFemale { get; set; }

    public bool BitDiabetes { get; set; }

    public bool BitHeartDisease { get; set; }

    public bool BitHypertension { get; set; }

    public bool BitAsthma { get; set; }

    public bool BitCholesterol { get; set; }

    public bool BitTuberculosis { get; set; }

    public bool BitSurgery { get; set; }

    public bool BitHospitalization { get; set; }

    public string VchOtherHistory { get; set; }

    public int? IntPainScore { get; set; }

    public bool BitFallRisk { get; set; }

    public string VchFallRiskRemarks { get; set; }

    public string VchOccupation { get; set; }

    public string VchSocialEconomicStatus { get; set; }

    public string VchFamilySupport { get; set; }

    public string VchPsychologicalStatus { get; set; }

    public int IntIhmsvisit { get; set; }

    public bool BitSendToDoctor { get; set; }

    public bool BitIsDoctorCompleted { get; set; }

    public int IntCode { get; set; }

    public int IntYr { get; set; }

    public int IntHmscode { get; set; }

    public virtual ICollection<TblNassessmentDoc> TblNassessmentDoc { get; set; } = new List<TblNassessmentDoc>();
}