// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblPermissionMas
{
    public int IntPermissionId { get; set; }

    public int FkRoleId { get; set; }

    public string VchModule { get; set; }

    public string VchSubModule { get; set; }

    public bool BitView { get; set; }

    public bool BitAdd { get; set; }

    public bool BitEdit { get; set; }

    public bool BitDelete { get; set; }

    public bool BitStatus { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public bool BitIsDeactivated { get; set; }

    public virtual TblRoleMas FkRole { get; set; }
}