// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblRoleMas
{
    public int IntId { get; set; }

    public string VchRole { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public bool BitIsActive { get; set; }

    public virtual ICollection<TblPermissionMas> TblPermissionMas { get; set; } = new List<TblPermissionMas>();

    public virtual ICollection<TblUsers> TblUsers { get; set; } = new List<TblUsers>();
}