// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblSystemicExamMas
{
    public int IntId { get; set; }

    public string VchSystemicExamination { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public int FkUserid { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public int? FkUpUser { get; set; }
}