// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblUserCompany
{
    public int IntId { get; set; }

    public int FkUseriId { get; set; }

    public int FkIntCompanyId { get; set; }

    public int? FkIntHmscode { get; set; }

    public string VchDoctorCode { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public virtual IndusCompanies FkIntCompany { get; set; }

    public virtual TblUsers FkUseri { get; set; }
}