// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblUsers
{
    public int IntUserId { get; set; }

    public string VchUsername { get; set; }

    public string HpasswordHash { get; set; }

    public string VchFullName { get; set; }

    public string VchEmail { get; set; }

    public string VchMobile { get; set; }

    public int FkRoleId { get; set; }

    public bool? BitIsDeActivated { get; set; }

    public DateTime? DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public string VchIpUsed { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }

    public string VchIpUpdated { get; set; }

    public string VchSignFileName { get; set; }

    public string VchSignFileAddress { get; set; }

    public string VchProfileFileName { get; set; }

    public string VchProfileFileAddress { get; set; }

    public virtual TblRoleMas FkRole { get; set; }

    public virtual ICollection<TblUserCompany> TblUserCompany { get; set; } = new List<TblUserCompany>();
}