// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.Models;

public partial class TblVitalsRange
{
    public int IntRangeId { get; set; }

    public string VchVitalName { get; set; }

    public decimal DecMinValue { get; set; }

    public decimal DecMaxValue { get; set; }

    public string VchUnitMeasure { get; set; }

    public bool BitIsDeactivated { get; set; }

    public DateTime DtCreated { get; set; }

    public string VchCreatedBy { get; set; }

    public DateTime? DtUpdated { get; set; }

    public string VchUpdatedBy { get; set; }
}