// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DWB.GroupModels;

public partial class GroupEntity : DbContext
{
    public GroupEntity(DbContextOptions<GroupEntity> options)
        : base(options)
    {
    }

    public virtual DbSet<IndusCompanies> IndusCompanies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IndusCompanies>(entity =>
        {
            entity.HasKey(e => e.IntPk);

            entity.Property(e => e.IntPk).HasColumnName("intPK");
            entity.Property(e => e.Add1)
                .HasMaxLength(100)
                .HasColumnName("add1");
            entity.Property(e => e.Add2)
                .HasMaxLength(80)
                .HasColumnName("add2");
            entity.Property(e => e.Add3)
                .HasMaxLength(80)
                .HasColumnName("add3");
            entity.Property(e => e.Add4)
                .HasMaxLength(80)
                .HasColumnName("add4");
            entity.Property(e => e.Bdate)
                .HasColumnType("smalldatetime")
                .HasColumnName("bdate");
            entity.Property(e => e.Brep)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("brep");
            entity.Property(e => e.CompanyType)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("company_type");
            entity.Property(e => e.CorpId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("corp_id");
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("INDIA")
                .HasColumnName("country");
            entity.Property(e => e.Cperson)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("cperson");
            entity.Property(e => e.Cphone)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("cphone");
            entity.Property(e => e.Descript)
                .HasMaxLength(80)
                .HasColumnName("descript");
            entity.Property(e => e.Descript1)
                .HasMaxLength(80)
                .HasColumnName("DESCRIPT1");
            entity.Property(e => e.Drep)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("drep");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Fdate)
                .HasColumnType("smalldatetime")
                .HasColumnName("fdate");
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.IsActive)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("isActive");
            entity.Property(e => e.Istnum)
                .HasMaxLength(80)
                .HasColumnName("istnum");
            entity.Property(e => e.Itnum)
                .HasMaxLength(80)
                .HasColumnName("itnum");
            entity.Property(e => e.Location).HasMaxLength(50);
            entity.Property(e => e.Lstnum).HasMaxLength(80);
            entity.Property(e => e.Mnt)
                .HasMaxLength(30)
                .HasColumnName("mnt");
            entity.Property(e => e.Phone1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("phone1");
            entity.Property(e => e.Phone2)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("phone2");
            entity.Property(e => e.Pwd)
                .HasMaxLength(25)
                .HasColumnName("pwd");
            entity.Property(e => e.Security)
                .HasMaxLength(1)
                .HasColumnName("security");
            entity.Property(e => e.SesCode).HasColumnName("ses_code");
            entity.Property(e => e.SsName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("")
                .HasColumnName("ss_name");
            entity.Property(e => e.State)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("state");
            entity.Property(e => e.Suser)
                .HasMaxLength(25)
                .HasColumnName("suser");
            entity.Property(e => e.Tdate)
                .HasColumnType("smalldatetime")
                .HasColumnName("tdate");
            entity.Property(e => e.UhidpreFix)
                .HasMaxLength(20)
                .HasColumnName("UHIDPreFix");
            entity.Property(e => e.VchDwbApi)
                .HasMaxLength(254)
                .IsUnicode(false)
                .HasColumnName("vchDwbApi");
            entity.Property(e => e.VchGstnumber)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("vchGSTNumber");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}