// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DWB.GroupModels;

public partial class IndusCompanies
{
    public int IntPk { get; set; }

    public int Id { get; set; }

    public string Descript { get; set; }

    public string Descript1 { get; set; }

    public string Add1 { get; set; }

    public string Add2 { get; set; }

    public string Add3 { get; set; }

    public string Add4 { get; set; }

    public string Email { get; set; }

    public string Itnum { get; set; }

    public string Lstnum { get; set; }

    public string Istnum { get; set; }

    public string Mnt { get; set; }

    public DateTime? Fdate { get; set; }

    public DateTime? Tdate { get; set; }

    public DateTime? Bdate { get; set; }

    public string Security { get; set; }

    public string Suser { get; set; }

    public string Pwd { get; set; }

    public short? SesCode { get; set; }

    public string Brep { get; set; }

    public string CompanyType { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Drep { get; set; }

    public string SsName { get; set; }

    public string CorpId { get; set; }

    public string Cperson { get; set; }

    public string Cphone { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string Location { get; set; }

    public string UhidpreFix { get; set; }

    public string IsActive { get; set; }

    public int? HeadOffice { get; set; }

    public string Vchgstnumber { get; set; }
}